version: '3.9'

services:

  ghost:
    env_file:
      - ./ghost_service_envars.env
      - ./mysql_service_envars.env
    image: ghost:${GHOST_VERSION:-4-alpine}
    restart: ${GHOST_RESTART_POLICY"-always}
    ports:
      - ${GHOST_HOST_PORT:-8080}:${GHOST_CONTAINER_PORT:-2368}
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: ${GHOST_DATABASE_CLIENT_NAME:?Error GHOST_DATABASE_CLIENT_NAME is empty. Please ensure it is set in the environment}
      database__connection__host: ${GHOST_DATABASE_SERVICE_NAME:?Error GHOST_DATABASE_SERVICE_NAME is empty. Please ensure it is set in the environment}
      database__connection__user: ${MYSQL_DATABASE_USER:?Error MYSQL_DATABASE_USER is empty. Please ensure it is set in the environment}
      database__connection__password: ${MYSQL_DATABASE_PASSWORD:?Error MYSQL_DATABASE_PASSWORD is empty. Please ensure it is set in the environment}
      database__connection__database: ${MYSQL_DATABASE_NAME:?Error MYSQL_DATABASE_NAME is empty. Please ensure it is set in the environment}
      # this url value is just an example, and is likely wrong for your environment!
      url: http://localhost:${HOST_PORT}
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    volumes:
      - type: bind
        source: ./code/ghost/content
        target: /var/lib/ghost/content

  db:
    env_file:
      - ./mysql_service_envars.env
    image: mysql:${MYSQL_VERSION:-5.7}
    restart: ${MYSQL_RESTART_POLICY:-always}
    environment:
      # DB Name, Useer and Password are required in addition to the root password for Ghost to connect
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?Error MYSQL_ROOT_PASSWORD is empty. Please ensure it is set in the environment}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME:?Error MYSQL_DATABASE_NAME is empty. Please ensure it is set in the environment}
      MYSQL_USER: ${MYSQL_DATABASE_USER:?Error MYSQL_DATABASE_USER is empty. Please ensure it is set in the environment}
      MYSQL_PASSWORD: ${MYSQL_DATABASE_PASSWORD:?Error MYSQL_DATABASE_PASSWORD is empty. Please ensure it is set in the environment}
    volumes:
      - type: bind
        source: ./code/mysql/conf.d
        target: /etc/mysql/conf.d