version: '3.9'

services:

  ghost:
    env_file:
      - ./ghost_service.env
    image: ghost:${GHOST_VERSION}
    container_name: casper
    hostname: ghost-blog
    restart: ${GHOST_RESTART_POLICY}
    ports:
      - ${GHOST_HOST_PORT}:${GHOST_CONTAINER_PORT}
    volumes:
      - type: bind
        source: ./data/ghost/content
        target: /var/lib/ghost/content
      - type: bind
        source: ./config/ghost/letsencrypt
        target: /etc/letsencrypt

  db:
    env_file:
      - ./mysql_service.env
    image: mysql:${MYSQL_VERSION}
    container_name: mysql-ghost
    hostname: mysql-ghost
    restart: ${MYSQL_RESTART_POLICY}
    volumes:
      - type: bind
        source: ./config/mysql/conf.d
        target: /etc/mysql/conf.d

  nginx:
    env_file:
      - ./nginx_service.env
    image: nginx
    container_name: nginx-front
    hostname: nginx-reversal
    volumes:
      - type: bind
        source: ./config/nginx
        target: /etc/nginx
    ports:
    - ${NGINX_HOST_PORT}:${NGINX_CONTAINER_PORT}