version: '3.9'

services:

  ghost:
    env_file:
      - ./ghost_service.env
    image: ghost:${GHOST_VERSION}
    restart: ${GHOST_RESTART_POLICY}
    ports:
      - ${GHOST_HOST_PORT}:${GHOST_CONTAINER_PORT}
    volumes:
      - ./data/ghost/content:/var/lib/ghost/content
      - ./config/ghost/letsencrypt:/etc/letsencrypt

  db:
    env_file:
      - ./mysql_service.env
    image: mysql:${MYSQL_VERSION}
    restart: ${MYSQL_RESTART_POLICY}
    volumes:
      - ./config/mysql/conf.d:/etc/mysql/conf.d

  web:
    env_file:
      - ./nginx_service.env
    image: nginx
    # volumes:
    #   - ./config/nginx:/etc/nginx
    ports:
    - ${NGINX_HOST_PORT}:${NGINX_CONTAINER_PORT}