version: '3.1'

services:

  ghost:
    image: ghost:4-alpine
    restart: always
    ports:
      - 8080:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://localhost:8080
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  secrets:
    mysql-root-password:
      file: ./mysql-db-root-password
      name: 0.0.1
    mysql-user-password:
      file: ./mysql-db-password
      name: 0.0.1
    mysql-user:
      file: ./mysql-db-user
      name: 0.0.1
    mysql-db-name:
      file: ./mysql-db-name
      name: 0.0.1
    